[package]
name = "codegenr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Errors
anyhow = "1.0.44"
thiserror = "1.0.30"
# File loading & path manipulations
url = "2.2.2"
path-dedot = "3.0.14"
reqwest = { version = "0.11", features = ["blocking"] }
walkdir = "2"
glob = "0.3"
# Json & Yaml manipulation
serde_json = { version = "1.0.68", features = ["preserve_order"] }
serde_yaml = "0.8.21"
serde = "1.0.68"
# Templating
handlebars = { version = "4.1.3", features =  ["script_helper"] }
# Regex
regex = "1"
once_cell = "1.8.0"
# Custom scripting
rhai = "1.2.1"

[dev-dependencies]
test-case = "1.2.1"
tempdir = "0.3"