[package]
name = "codegenr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = { version = "1.0.68", features = ["preserve_order"] }
serde_yaml = "0.8.21"
serde = "1.0.68"
anyhow = "1.0.44"


[dev-dependencies]
test-case = "1.2.1"
