name: Dev

on:
  workflow_dispatch:
  push:
    branches: ["dev**", "release**"]
    paths-ignore:
      - ".github/workflows/main.yaml"
      - ".vscode/**"
      - "_assets/**"
      - "**.md"
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest] 
# , windows-latest
    env:
      RUST_LOG: debug
     
    steps:
      - name: Show rustup toolchain version
        run: rustup show

      - uses: actions/checkout@v2

      - name: Unit tests
        run: |
          cargo test --workspace

      - name: Build
        run: |
          cargo build --workspace
