name: Main

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore:
      - ".github/workflows/dev.yaml"
      - ".vscode/**"
      - "_assets/**"
      - "**.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    env:
      RUST_LOG: debug
     
    steps:
      - name: Show rustup toolchain version
        run: rustup show

      - uses: actions/checkout@v2

      - name: Unit tests
        run: |
          cargo test --workspace

      - name: Build
        run: |
          cargo build --workspace --release

  publish:
    needs: tests
    runs-on: ubuntu-latest
    env:
      RUST_LOG: debug

    steps:
      - name: Show rustup toolchain version
        run: rustup show

      - uses: actions/checkout@v2

      - name: PublishTool
        run: |
          cargo login ${{ secrets.CRATES_IO_CODEGENR_PUBLISH_TOKEN }}
          cd codegenr
          cargo publish
